dist: bionic
language: node_js
node_js: 'lts/*'

services:
  - docker

branches:
  only:
    - develop
    - master    
    - /^(release).*$/
    # OPS-1664 naming convention <branch>/<JIRA-Ticket ID>-<Jira_Summary>
    - /^(feature\/[A-Z]+-[0-9]+-[a-zA-Z0-9_]+)$/

stages:
  - name: test
    if: NOT ( (commit_message =~ /(skip-test-stage)/ ) OR branch = master OR branch = develop OR branch = /^(feature).*$/ AND "$TRAVIS_PULL_REQUEST" != "false" )
  - name: deploy
    if: NOT (commit_message =~ /(skip-deploy-stage)/)
jobs:
  include:
    - stage: test
      name: test e2e echo
      script:
        - echo "test e2e"
        - echo "Line_TWO"
    - stage: build
      if: NOT fork
      script:
        - ./build.sh
      name: build and push
      language: generic
      env:
        - GIT_SHA=$( git rev-parse HEAD )
        - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
      install:
        - mkdir -p .build
        - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in travis_rsa.enc -out .build/travis_rsa -d
