apiVersion: v1
kind: ConfigMap
metadata:
  name: $SERVICE_NAME-environment-variables
data:
  THIS_SERVICE: $SERVICE_NAME
  BRANCH: $NAMESPACE
  DB_URL: mongodb://10.141.10.250:27017/schulcloud_$NAMESPACE
  NODE_ENV: production
  PORT: '3030'
  LOG_LEVEL: info
  # for running backup.js to setup database
  MONGO_HOST: '10.141.10.250'
  MONGO_DATABASE: schulcloud_$NAMESPACE
  JWT_AUD: $STAGING_DOMAIN
  CALENDAR_API_KEY: "123"
  CALENDAR_URI: http://schulcloud-calendar:3000